### ISSUE TITLE
ImportError: No module named 'bitcoin'

### ISSUE THREAD

**Issue by popmechanic** [OpenAssets/colorcore#1]
I've just finished installing bitcoind from source on Ubuntu 14.04, and running it with the server and daemon arguments. After installing colorcore and all of its dependencies, I'm getting the following error after amy attempt to execute the script:

<code>python3 colorcore.py --help
Traceback (most recent call last):
  File "colorcore.py", line 31, in <module>
    import colorcore.routing
  File "/home/colorcore/colorcore/routing.py", line 26, in <module>
    import bitcoin.core
ImportError: No module named 'bitcoin'</code>

Perhaps the server is still downloading / building the blockchain? Any other ideas what may be causing this issue?

**Comment by Flavien** [comment]
This is probably because the dependencies get installed for Python 2.
First, ensure that you have Python 3.4 installed:

```
sudo add-apt-repository ppa:fkrull/deadsnakes
sudo apt-get update
sudo apt-get install python3.4
```

Then install the requirements for Python 3:

```
sudo python3.4 -m ensurepip
sudo pip3.4 install --upgrade setuptools
sudo pip3.4 install --upgrade -r requirements.txt
```

After this, the dependencies should be properly installed for Python 3, and this should work: `python3 colorcore.py --help`.

**Comment by popmechanic** [comment]
That worked, thanks!
