### ISSUE TITLE
Unable to see incoming colored transactions

### ISSUE THREAD

**Issue by ganeshjung** [OpenAssets/colorcore#11]
Hi,

When receiving colored coins I would like to know the assets and amount that arrive as soon as I see the transaction in bitcoind.

I have tried listunspent, but it only shows me the transactions with at least 1 confirmation. Is there a way to check the assets that are contained in a transaction without using the coinprism explorer?

Any help is highly appreciated.

Regards,
Ganesh

**Comment by Flavien** [comment]
You have to set the `minconf` argument to 0 to get unconfirmed transactions as well. By default, it is set to 1.

**Comment by ganeshjung** [comment]
Hi Flavien,

Thank you for helping. How do I set this parameter? I have tried adding a line "minconf=0" to config.ini without success.

Regards,
Ganesh

**Comment by Flavien** [comment]
You need to set it when calling `listunspent`. Just add a POST parameter `minconf=0`.

**Comment by ganeshjung** [comment]
Is there a way to set this parameter when using the Python command line?

**Comment by ganeshjung** [comment]
I've tested minconf=0 as a POST parameter on the API and it works.
