### ISSUE TITLE
Get OpenAssets address for given Bitcoin address

### ISSUE THREAD

**Issue by ganeshjung** [OpenAssets/colorcore#12]
Hi,

when receiving assets I would like to generate a new address. I can generate an address with bitcoind, but this doesn't give me the corresponding OpenAssets address. In getbalance/listunspent a new address is only visible and converted to OpenAssets format after it has received a transactions.

Is there a way to use the API to convert an arbitrary bitcoin address?

Any help is highly appreciated.

Kind regards,
Ganesh

**Comment by Flavien** [comment]
You can obtain the Open Assets address by decoding the original base 58 address, prepending the byte 19, and re-encoding in base 58 (making sure you recompute the checksum).

See the specification [here](https://github.com/OpenAssets/open-assets-protocol/blob/master/address-format.mediawiki).

**Comment by ganeshjung** [comment]
Hi Flavien,

thank you for the suggestion. Yes, we can implement the address translation. Still I would prefer using the translation that is implemented in the colorcore to avoid reimplementing it. 

getbalance only gives me the translation for the addresses that have already received an input. Maybe there is a chance to get the translation of all addresses the bitcoind has in stack from colorcore?

Kind regards,
Ganesh

**Comment by Flavien** [comment]
If you set the `address` parameter when calling `getbalance`, you will receive the corresponding asset address.

**Comment by ganeshjung** [comment]
Thank you. I've tried this, works!
