### ISSUE TITLE
Create color definition using color core?

### ISSUE THREAD

**Issue by popmechanic** [OpenAssets/colorcore#2]
After creating an asset using color core, Color Prism's block chain explorer represents the asset as, "Unnamed colored coins." e.g. https://www.coinprism.info/tx/d687a67e9fc605b73956f556611baf84421df2384e0c61a401c42ddd0410f81f

Is there a way to use color core to create a color name and definition?

**Comment by Flavien** [comment]
Yes, you need to specify a metadata string when issuing the colored coins (`--metadata` argument), with the following format:

```
--metadata u=https://mysite.com/assetinfo
```

Where `https://mysite.com/assetinfo` is a link to the asset definition file.

The asset definition file is a JSON file and should have the following format:

```
{
  "source_addresses": [
    "3Kfotk3zahcW2R94fdXWRtrR7b5Bn98Jy3"
  ],
  "contract_url": "http://lemon.ad/LEMO-info",
  "name_short": "LEMO",
  "name": "Lemonade Stand Revenue Share",
  "issuer": "The Little Lemonade Stand",
  "description": "This token represents a share of ownership in the little lemonade stand in my street. Each token grants right to 1% of the monthly profits from my stand.",
  "description_mime": "text/x-markdown; charset=UTF-8",
  "type": "CryptoToken",
  "divisibility": 4,
  "link_to_website": true,
  "icon_url": "http://lemon.ad/LEMO/icon.jpg",
  "image_url": "http://lemon.ad/LEMO/image.jpg",
  "version": "1.0"
}
```

`source_address` must match the source address of the asset, and `divisibility` determines how many units makes one of your coin (in power of 10). So with 4, 10,000 units is one LEMO coin, which means each coin can be divided 10,000 times. The other fields should be self explanatory.

The file can be hosted on any server, but the URL should be at most 25 characters to ensure it can fit in an OP_RETURN output and be embedded in the Blockchain (URL shorteners can be used).

**Comment by popmechanic** [comment]
I was able to successfully use the --metadata argument to issue a new asset:

python3.4 colorcore.py issueasset --metadata u=http://chroma.io/crystal.json 1JwRLvWB9W1GK9KWJYJie5gMenYKnK2ZPd 100

It returned this transaction hash:
49baef877fe87688560c68264c8e06663e1a6b26b61f4e0a42dda26341cc864e

But inspecting this hash reports the coins as unnamed colored coins:
https://www.coinprism.info/tx/49baef877fe87688560c68264c8e06663e1a6b26b61f4e0a42dda26341cc864e

Also, retrieving the balance through color core shows that the asset was thrown in with previous issuances that didn't use the metadata argument:

```
[
    {
        "assets": [
            {
                "quantity": "500",
                "asset_address": "3QY9panGLtxGa8epDDPqUBmzJecyVHYgvJ"
            }
        ],
        "value": "0.00950000",
        "address": "1JwRLvWB9W1GK9KWJYJie5gMenYKnK2ZPd"
    }
]
```

Is my json correctly specified?
http://chroma.io/crystal.json

**Comment by Flavien** [comment]
The `source_address` field is wrong, it should be: `3QY9panGLtxGa8epDDPqUBmzJecyVHYgvJ` in your case.

> Also, retrieving the balance through color core shows that the asset was thrown in with previous issuances that didn't use the metadata argument

The last issuance specifying metadata overwrites metadata (or lack thereof) for previous issuances of the same asset. So if you successfully associate your asset with metadata, previous issuances will also be associated with that same metadata.

Also note that it can take up to 6 hours after changing the metadata file for the information on Coinprism to be refreshed.

**Comment by popmechanic** [comment]
The source address is only created after an issueasset command, correct? So is the best way to create a metadata definition to:

1) Use issueasset without the metadata argument to issue a single coin
2) capture the asset address
3) specify that asset address in the json metadata file 
4) Execute another issueasset command using this metadata to create the rest of the coins

Or is there a way to create the asset address before coloring the coins?

**Comment by Flavien** [comment]
The source address can actually be derived entirely offline, from the address used to issue the tokens (in your case `1JwRLvWB9W1GK9KWJYJie5gMenYKnK2ZPd`). The process is described in the [specification](https://github.com/OpenAssets/open-assets-protocol/blob/master/specification.mediawiki#protocol-overview):  `script_hash = RIPEMD160(SHA256(script))` where script is the P2PKH script for your address.

You are right that it is not exposed from Colorcore, but perhaps we can add it if you need it. The process you described also works (first issue to check the asset address).

**Comment by popmechanic** [comment]
Ah, this makes sense. Thank you for walking me through it. Asset issuance with metadata is a desirable feature for us.
