### ISSUE TITLE
Send to Multiple receipients

### ISSUE THREAD

**Issue by wdl1908** [OpenAssets/colorcore#5]
I'm looking at the source of openassets and noticed it is possible to specify multiple destinations but colorcore does not support multiple destinations. Would it be technically possible to implement this? I would do the work but before I start with that I would like to know if it's possible.

The strange thing in openassets is that it would add the same source multiple times.

**Comment by Flavien** [comment]
Yes it should be possible to add this functionality. If you use the [openassets](https://github.com/OpenAssets/openassets/blob/master/openassets/transactions.py) library, it should be as simple as crafting a "transfer spec" that sends to multiple recipients.

Let me know if you have questions.
