### ISSUE TITLE
bitcoind dependency is onerous

### ISSUE THREAD

**Issue by donpdonp** [OpenAssets/colorcore#6]
Given the chain.com API to look up addresses and transactions, is a local wallet necessary? Running bitcoind means 30GB of disk to hold the blockchain (as of March 2015). Could a sqlite table of issued assets fill the same job? Thanks.

**Comment by Flavien** [comment]
if you use the chain.com provider (`blockchain-provider=chain.com`), then you don't need a local wallet or the blockchain on your disk. You can query any address on the blockchain.

Obviously, you won't be able to sign transactions.

**Comment by donpdonp** [comment]
Ok I'm looking at still being able to create assets. Has it been looked at to use the new bitcoin-tx tool? bitcoin-tx can sign transactions using given private keys w/o using bitcoind. The private key could be specified to the colorbase.py issue command perhaps.

**Comment by donpdonp** [comment]
Also, chain.com can sign transactions. 
https://chain.com/docs#bitcoin-transaction-sign

**Comment by Flavien** [comment]
You should be able to create an unsigned transaction via Colorcore by specifying `unsigned` for the `mode` parameter. You can then sign it from your Bitcoin library of choice or Chain as you mentionned (but in that case you are sending them your private keys).

Then you can broadcast it using any API such as Chain, Blockchain.info, or even the Coinprism API.

**Comment by donpdonp** [comment]
ok I'll look at that approach thanks!
