### ISSUE TITLE
RegTest addresses

### ISSUE THREAD

**Issue by dazraf** [OpenAssets/colorcore#9]
Hello,

I'm running a regtest server - the addresses generated by the server are not valid. I assume this is expected behaviour. Base58Address and bitcoin.wallet.CBitcoinAddress requires valid addresses. Is there a way of running colorcore with a regtest server? 

Thanks
Fuzz.

**Comment by Flavien** [comment]
You probably need to modify the settings file with the version bytes used by the regtest network:

```
[environment]
# These are the settings for MainNet
version-byte=0
p2sh-version-byte=5
```
